(* auto-generated by gt *)

let parsed =   let lexbuf = Lexing.from_channel (if(Array.length(Sys.argv) > 1) then (open_in Sys.argv.((Array.length Sys.argv) - 1)) else (stdin)) in   Gra2srs_parse.main Gra2srs_lex.token lexbuf;;
let rec is_flag arg args i =
	 if(i = (Array.length args)) then false
	else if(arg = args.(i)) then true
	else (
		 is_flag arg args (i + 1)
	)
;;if(is_flag "-p" Sys.argv 0 || (Array.length Sys.argv = 2 || Array.length Sys.argv = 1)) then (
	match parsed with
   	None -> ()
   	| Some(x) -> Gra2srs_pp.pp print_string true x
);;


print_string "\n\n\n";;

if(is_flag "-a" Sys.argv 0) then (match parsed with
   None -> ()
   | Some(x) -> Gra2srs_ppast.ppast print_string false x
);;

print_string "\n";;

if(is_flag "-g" Sys.argv 0) then (
	match parsed with
   	None -> ()
   	| Some(x) -> Gra2srs_gviz.gviz print_string false "" x
);;


print_string "\n\n\n";;

